{"timestamp":"2025-10-05T11:16:50.567421Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-05T11:16:50.569149Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retail_transaction.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-05T11:16:50.580336Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/retail_transaction.py","lineno":5,"logger":"py.warnings"}
{"timestamp":"2025-10-05T11:16:50.608435Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.609948Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.610984Z","level":"info","event":"Current task name:extract_task","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.611915Z","level":"info","event":"Dag name:etl_retail_transactions_fix","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.626434Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.UndefinedTable) relation \"public.retail_transactions\" does not exist\nLINE 1: SELECT * FROM public.retail_transactions\n                      ^\n\n[SQL: SELECT * FROM public.retail_transactions]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/retail_transaction.py","lineno":76,"name":"extract"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":682,"name":"read_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":1776,"name":"read_query"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":1599,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1770,"name":"exec_driver_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1674,"name":"_exec_driver_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"UndefinedTable","exc_value":"relation \"public.retail_transactions\" does not exist\nLINE 1: SELECT * FROM public.retail_transactions\n                      ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-05T11:16:50.647311Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.648485Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.649772Z","level":"info","event":"Task:<Task(PythonOperator): extract_task>","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.650855Z","level":"info","event":"Failure caused by (psycopg2.errors.UndefinedTable) relation \"public.retail_transactions\" does not exist","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.651856Z","level":"info","event":"LINE 1: SELECT * FROM public.retail_transactions","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.652511Z","level":"info","event":"                      ^","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.653696Z","level":"info","event":"","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.654690Z","level":"info","event":"[SQL: SELECT * FROM public.retail_transactions]","logger":"task.stdout"}
{"timestamp":"2025-10-05T11:16:50.655553Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"task.stdout"}
